// Core/Services/ToolRegistry.swift
// Central registry for all tools. FROZEN after Phase 1.
// Wave-2 tool plans overwrite their own *Definition.swift stub — this file NEVER changes.
// Source: RESEARCH.md Pattern 3 [VERIFIED]

import Observation

@Observable
final class ToolRegistry {
    let tools: [ToolDefinition]

    init() {
        // All 7 tool slots pre-registered. Wave-2 plans overwrite *Definition.swift stubs.
        // FREEZE MARKER: Wave-2 tool plans do NOT edit this file — they own their *Definition.swift.
        tools = [
            JSONFormatterDefinition.make(),
            Base64Definition.make(),
            URLEncoderDefinition.make(),
            JWTDefinition.make(),
            TimestampDefinition.make(),
            HashDefinition.make(),
            UUIDDefinition.make(),
        ]
    }

    /// Search tools by name or keyword. Returns all tools when query is empty.
    func search(_ query: String) -> [ToolDefinition] {
        guard !query.isEmpty else { return tools }
        let q = query.lowercased()
        return tools.filter { tool in
            tool.name.localizedCaseInsensitiveContains(q) ||
            tool.keywords.contains { $0.localizedCaseInsensitiveContains(q) }
        }
    }

    /// First-match-wins detection predicate chain (D-06).
    /// Ordered: JSON → JWT → Base64 → URL-encoded → URL → Timestamp → UUID
    func detect(from string: String) -> DetectionResult? {
        for tool in tools {
            if let result = tool.detectionPredicate?(string) { return result }
        }
        return nil
    }
}
